apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.pvc.name }}
spec:
  resources:
    requests:
      storage: {{ .Values.pvc.requests.storage }}
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.storageClassName }}