apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.application.name }}-svc
spec:
  selector:
    app: {{ .Values.application.name }}
  type: LoadBalancer
  ports:
  - port: {{ .Values.service.loadbalancer.port }}
    nodePort: 30000
    targetPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mysql.name }}
spec:
  selector:
    app: {{ .Values.mysql.name }}
  ports:
  - port: 3306

