apiVersion: v1
kind: PersistentVolume
metadata:
  name: fast-n-foodious-ms-produto-pv
spec:
  capacity:
    storage: 500Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: fast-n-foodious-ms-produto-storage
  hostPath:
     path: /Users/renatorodrigues/mysql-produto
     type: DirectoryOrCreate