apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fast-n-foodious-ms-produto-pvc
spec:
  resources:
    requests:
      storage: 500Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: fast-n-foodious-ms-produto-storage